from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import os
from dotenv import load_dotenv

load_dotenv()

model = ChatOllama(model=os.getenv("OLLAMA_MODEL_NAME", "qwen2.5:7b"),
                   temperature=0,
                   base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
                   )

labels = {"AI": 0,
          "HUMAN": 1}

prompt = """You are an expert text authenticity classifier. Your task is to analyze whether the given text was written by a human or generated by an AI language model.

Analyze the text for the following indicators:

AI-generated signals:
- Overly structured or formulaic writing (excessive use of bullet points, numbered lists, balanced paragraphs)
- Unnaturally consistent tone throughout — no emotional variation, hesitation, or personality shifts
- Generic, safe, or hedge-heavy language ("it is important to note", "it is worth mentioning", "in conclusion")
- Perfect grammar with no colloquialisms, typos, or informal shortcuts
- Repetitive sentence structure or rhythm
- Broad, surface-level coverage of topics without personal experience or opinion
- Lack of contradictions, tangents, or irrelevant details that humans naturally include
- Transitions that feel mechanical or templated
- Answers that are suspiciously complete, balanced, and neutral

Human-written signals:
- Personal anecdotes, emotions, or subjective opinions
- Grammatical errors, typos, informal punctuation (e.g., "..." "!!!")
- Inconsistent tone — emotional, frustrated, excited, casual
- Incomplete thoughts, run-on sentences, or abrupt endings
- Slang, idioms, or culturally specific language
- Redundancies or contradictions
- Strong personal bias or one-sided views
- Unusual or unique phrasing

Multilingual note:
Apply the same analysis regardless of language. Russian, Chinese, Arabic, and other languages have their own AI vs. human writing patterns — apply equivalent criteria for each language's natural writing style and common AI artifacts in that language.

Analyze the text carefully, then respond with a single word only.

Rules:
- Output ONLY one word: AI or HUMAN
- Do not explain your reasoning
- Do not add punctuation, newlines, or any other text

Text to analyze:
\"\"\"
{text}
\"\"\"
"""

prompt_template = ChatPromptTemplate.from_messages([
    ("system", "You are an expert text authenticity classifier. Your task is to analyze whether the given text was written by a human or generated by an AI language model."),
    ("system", prompt),
    ("human", "AI or HUMAN"),
])

output_parser = StrOutputParser()

chain = prompt_template | model | output_parser

def get_plagiarism_score(text):
    return chain.invoke({"text": text})

def convert_text_to_label(text):
    return labels[text.strip().upper()]

if __name__ == "__main__":
    text = "Hello, neighbour"
    score = get_plagiarism_score(text)
    label = convert_text_to_label(score)
    print(f"Plagiarism score: {score}, Label: {label}")
